---
title: "The dplyr Library for Data Manipulation Part-1"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
```

```{r}
# Load the Motor Trend Car Road Tests (mtcars) dataset
carData = read.csv('/Users/s0k04ng/Downloads/mtcars.csv')
#carData = data('mtcars')

# Print the first five rows (or samples) in the data frame
head(carData, 5)

# Print the structure of the data frame 
str(carData)

# Print the names of the columns (features or variables)
colnames(carData)

# Print the number of samples (rows) and features (columns) in the data frame
nrow(carData)
ncol(carData)
```

```{r}
# Create a vector of categorical columns
categorical_cols = c('vs', 'am')

# Convert the columns to factor type
carData[categorical_cols] = lapply(carData[categorical_cols], as.factor)

# Print the structure of the resulting dataframe
str(carData)
```

```{r}
# Select only the feature wt
select(carData, wt)
```

```{r}
# Select everything except the feature wt
select(carData, -wt)
```

```{r}
# Select only the features cyl and wt
select(carData, c(cyl,wt))
```

```{r}
# Select everything except the features cyl and wt
select(carData, -c(cyl,wt))
```

```{r}
# Filter cars with V-shaped engine 
filter(carData, vs == 0)
```

```{r}
# Filter cars with V-shaped engine and manual transmission
filter(carData, vs == 0 & am == 0 )
```

```{r}
# Filter cars with V-shaped engine and manual transmission
# and hp greater than 150 or less than 100
filter(carData, vs == 0 & am == 1 &(hp <100 | hp >150))
```

```{r}
# Select only the feature cyl and wt for cars with v-shaped engine
carData %>%  filter(vs == 0) %>% select(cyl, wt)
#filter(carData, vs == 0)
```

```{r}
# Select only the feature cyl and wt for cars with v-shaped engine
# and hp greater than 150
carData %>%  filter(vs == 0 & hp >150) %>% select(cyl, wt)
```

```{r}
# Create a new column called wtton
mutate(carData, wtton = 0.45*wt)
```

```{r}
# Create a new column called wtton by ensuring
# cars with NA weight values are negelected
carData %>% filter(!is.na(wt)) %>% mutate(wtton = 0.45*wt)
```

```{r}
# Check if wtton is a new column in the dataframe
#colnames(carData)
carData = carData %>% filter(!is.na(wt)) %>% mutate(wtton = 0.45*wt)
colnames(carData)
```

```{r}
# Add a new column called cyltype with value High
# is cyl is greater than 4 and Low otherwise
carData %>% mutate(cyltype = ifelse(cyl >4, 'High', 'Low'))
```

```{r}
# Create a new data frame with the cyltype and wtton added
carData.new = carData %>% mutate(cyltype = ifelse(cyl >6, 'High', 'Low'), wtton = 0.45*wt)
head(carData.new, 5)
```

```{r}
# Return the mean weight (in tons) of the cars
carData.new %>% summarise(mean(wtton))
carData.new %>% summarise(mean(wtton),mean(disp))
carData.new %>% summarise(mean(wtton),min(disp))
```
```{r}
# Return the mean weight (in tons) and mean displacement
# of the cars
carData.new %>% group_by(cyltype) 
carData.new %>% group_by(cyltype) %>% summarise(mean(wtton),mean(disp))
```

```{r}
# Group cars according to cyltype and calculate mean weight and
# mean displacement
carData.new %>% group_by(cyltype) %>% summarise(mean(wtton),mean(disp))
```

```{r}
# Group cars according to cyltype and calculate mean weight and
# minimum displacement
carData.new %>% group_by(cyltype) %>% summarise(mwt= mean(wtton),mdisp = min(disp))
carData.new %>% group_by(cyltype) %>% summarise(mwt= mean(wtton),mdisp = min(disp)) %>% arrange(mwt)

carData.new %>% group_by(cyltype) %>% summarise(mwt= mean(wtton),mdisp = min(disp)) %>% arrange(desc(mwt))
```

```{r}
# Group cars according to cyltype and calculate mean weight and
# minimum displacement followed by arranging in increasing order
# of mean weight
carData.new %>% 
```

```{r}
# Return number of samples for each cyltype
carData.new %>% group_by(cyltype) %>% count()
```

```{r}
# Return number of samples for each cyltype and vs
carData.new %>%  count(cyltype, vs)
```

```{r}
# Return number of samples for each cyltype and sort by
# increasing order of count
carData.new %>% count(cyltype) %>% arrange(n)
```
