---
title: "Simulation Using R In-built Functions"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
# A fun exercise to simulate the rolling of a fair die
# Sampling space for rolling a pair of fair dice
s = c(1:6)

# Corresponding probabilities
p = 1/6*replicate(6, 1)
print(p)

# The sampling process
sample(s, 1, replace = TRUE, prob = p)
sample(s, 2, replace = TRUE, prob = p)

nsimulations =10
#replicate(nsimulations, sample(s, 1, replace = TRUE, prob = p))

simulatedData = replicate(nsimulations, sample(s, 2, replace = TRUE, prob = p))
str(simulatedData)
print(simulatedData)
```

```{r}
nsimulations =1e5
simulatedData = replicate(nsimulations, sample(s, 2, replace = TRUE, prob = p))
# Function to check if the sum of the rolls is at least 7
checkEvent = function(data){
  if (sum(data) >= 7){
    return(1)
  } else {
    return(0)
  }
}

# Probability that the sum of the rolls is at least 7
#print(simulatedData)
apply(simulatedData, 2, checkEvent)
mean(apply(simulatedData, 2, checkEvent))
# Function to check if the first roll is even
checkEvent1 = function(data){
  if (data[1] %% 2 ){
    return(1)
  } else {
    return(0)
  }
}

# Probability that the first roll is even
mean(apply(simulatedData, 2, checkEvent1))
```

```{r}
# Simulating a discrete random variable (n=10, p =0.6)
n = 10
p = 0.6
nsimulations = 1e05
simulatedData = rbinom(nsimulations, n, p)
df = as.data.frame(table(simulatedData))
colnames(df) = c('Value', 'Frequency')
#head(df)
p = ggplot(data =df ) + 
  geom_col(aes(x = Value, y =Frequency), width = 0.7 , fill = 'steelblue') +
  labs(x = 'Value' , y = 'Frequency')
  ggtitle('Simulating binomial random variable') +
  theme_minimal()
p
#rpois(100, lambda = 10)
```

```{r}
# Simulating a continuous random variable
mu =170
sigma =8
nsimulations = 1e05
simulateddata = rnorm(nsimulations, mean =mu, sd = sigma )
df = as.data.frame(simulateddata)
colnames(df) = 'Height'
#head(df)
#mean(df['Height'] >=170 & df['Height'] <=171 )
delta =2
p1 = ggplot(data =df ) + 
  geom_histogram(aes(x = Height, y = ..count..), breaks = seq(mu-4*sigma, mu+4*sigma, by = delta), color = 'black' , fill = 'steelblue', alpha = 0.4) +
labs(x = 'Height' , y = 'Frequency')
p1

```



