---
title: "Webinar 6"
editor_options:
  chunk_output_type: inline
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
library(HSAUR)
library(ggcorrplot)
library(reshape2)
library(car)
```

```{r}
# Set ggplot theme for plotting
My_Theme = theme(axis.text.x = element_text(size = 9),
   axis.text.y = element_text(size = 9),
   axis.title.x = element_text(size = 11),
   axis.title.y = element_text(size = 11),
   plot.title = element_text(size = 12, hjust = 0.5, face = "bold"))
```


```{r}
# Simulate age of 100 senior adults in years
n = 100
age_years = round(rnorm(n, mean = 50, sd = 10), 0)
print(age_years)
```

```{r}
# Create a copy of the age variable to reflect age in months
age_months =12*age_years
print(age_months)
```

```{r}
# Create another copy that adds a bit of noise to the age (in years) variable
age_noisy = age_years + rnorm(n, mean = 0, sd = 4)
print(age_noisy)
```

```{r}
# Simulate a population model for height as a function of age (in years)
height = 20 + 3*age_years + rnorm(n, mean = 0, sd = 10)
print(height)
```

```{r}
# Create a dataframe with all the predictors (age in years, age in months, noisy age in years) and the response (height in cm)
hData = data.frame(age_years, age_months, age_noisy, height)
head(hData)
```

```{r}
# A quick way to visualize the relationship between the response and individual predictors
pairs(hData)

```

```{r}
# Calculate correlation matrix for all predictors
cormat = round(cor(hData %>% select(-c(height))), 2)
print(cormat)
```

```{r}
# Set lower-triangular part of correlation matrix to NA
cormat[lower.tri(cormat)] = NA
print(cormat)
```

```{r}
# Melt the correlation matrix
melt(cormat)
```

```{r}
# Visualize the correlation matrix using ggplot
p = ggplot(data = melt(cormat), aes(x = Var2, y = Var1, fill = value)) +
  geom_tile(color = 'white') +
  coord_fixed() +
  scale_fill_gradient2(low = 'blue', high = 'red', mid = 'white', midpoint = 0, limit = c(-1, 1), space = 'Lab', name = 'Correlation')
p
```

```{r}
# Visualize the correlation matrix using ggcorrplot
ggcorrplot(cormat)
```

```{r}
# Build a linear regression model for height as a function of age (in years)
hData_sample = hData[sample(n, 20), ]
model_years = lm(data = hData_sample, height ~ age_years)
summary(model_years)
```

```{r}
# Build a linear regression model for height as a function of age (in months)
model_months = lm(data = hData_sample, height ~ age_months)
summary(model_months)
```

```{r}
# Build a linear regression model for height as a function of age (in years, noisy version)
hData_sample = hData[sample(n, 20), ]
model_noisy = lm(data = hData_sample, height ~ age_noisy)
summary(model_noisy)
```

```{r}
# Build a linear regression model for height as a function of age (in years) and age (in months)
model = lm(data = hData_sample, height ~ age_years + age_months)
summary(model) 
```

```{r}
# Build a linear regression model for height as a function of age (in years) and age (in years, noisy version)
hData_sample = hData[sample(n, 20), ]
model = lm(data = hData_sample, height ~ age_years + age_noisy)
summary(model) 
```

```{r}
## Assess multicollinearity using VIF
hData_sample = hData[sample(n, 100), ]
model = lm(data = hData_sample, height ~ age_years + age_noisy)
car::vif(model)
```

```{r}
# Load the mtcars dataset
carData = read.csv('Data/mtcars.csv', header = TRUE)
cData = carData %>% select(c('mpg', 'hp', 'wt', 'disp'))
head(cData)
```

```{r}
# Model with intercept
model = lm(data = cData, mpg ~ hp + wt)
summary(model)
```

```{r}
# Intercept-free model
model = lm(data = cData, mpg ~ 0 + hp + wt)
summary(model)
```


```{r}
# Data on salaries of employees in IT based on
# their years of experience (X)
# their education level (1 = High school diploma, 2 = Bachelor of Science, 3 = Advanced degree) (E)
# whether or not they are management (1 = management responsibility, 0 = not management) (M)
dfSalary = read.csv('Data/salary.csv', header = TRUE)
str(dfSalary)
```


```{r}
# Rename columns
dfSalary = dfSalary %>% rename(Salary = S, Experience = X, Education = E, Management = M)
head(dfSalary, 2)
```


```{r}
# Convert education level and management to factors
categorical_cols = c('Education', 'Management')
dfSalary[categorical_cols] = lapply(dfSalary[categorical_cols], as.factor)
str(dfSalary)
```

```{r}
# Plot salary w.r.t. experience color and shape coded using education and experience
p4 = ggplot(data = dfSalary) + 
  geom_point(aes(x = Experience, y = Salary, color = Education)) +
   labs(x = 'Experience', y = 'Salary') + 
   ggtitle("Salary of Experienced IT Employees") +
   My_Theme
p4
```

```{r}
# Build a linear regression model for Salary as a function of Experience, Education, and management 
model = ?
```

```{r}
# A snapshot of the design matrix
?
```

```{r}
# Compare the design matrix entries with the dataframe entries
head(dfSalary, 10)
```

```{r}
# Comparing the effect of management roles across different education levels
p5 = ggplot(data = dfSalary) +
  geom_boxplot(aes(x = Education, y = Salary)) +
  ? +
  ggtitle('Salary of IT Employees')
p5
?
```

```{r}
# Histogram of salaries corresponding to Education level 3
df = ?
p6 = ggplot(data = df) +
  geom_histogram(aes(x = Salary), binwidth = 1500)
p6
```


```{r}
# Comparing the effect of management roles across different education levels
p6 = ggplot(data = dfSalary) + 
  
p6
```

```{r}
# Build a linear regression model for Salary as a function of Experience, Education, and interaction between Experience and Education 
model1 = ?
```


```{r}
# Build a linear regression model for Salary as a function of Experience, Education, Management, and interaction between Experience and Education 
model2 = ?
```

