---
title: "Webinar 2 Sunday, May 4, 2025"
editor_options:
  chunk_output_type: inline
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
# Load the house price dataset
hData = read.csv('/Users/s0k04ng/Downloads/houseprices.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c("", "NA", "Not Available", "not available", "n/a"))
str(hData)
```

```{r}
# Convert 'locality', 'facing' and 'parking' columns to factors
categorical_cols = c('locality', 'facing', 'parking')
hData[categorical_cols] = lapply(hData[categorical_cols], as.factor)
str(hData)
```

```{r}
# Continuous columns
continuous_cols = setdiff(colnames(hData), categorical_cols)
```

```{r}
# Set ggplot theme for plotting
My_Theme = theme(axis.text.x = element_text(size = 9),
   axis.text.y = element_text(size = 9),
   axis.title.x = element_text(size = 11),
   axis.title.y = element_text(size = 11),
   plot.title = element_text(size = 12, hjust = 0.5, face = "bold"))
```

```{r}
# Plot percentage of NAs in each column of the data frame
hData_NA = setNames(stack(sapply(hData, function(x){(sum(is.na(x))/length(x))*100}))[2:1], c('Feature','Value'))
p = ggplot(data = hData_NA, aes(x = Feature, y = Value)) +
  geom_bar(stat = 'identity', fill = 'steelblue', width = 0.3) +
  theme(text = element_text(size = 14, face = 'bold'),
  axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  xlab('') + ylab('Percentage') +
  ggtitle('Percentage of NAs across all features') +
  My_Theme
p
```

```{r}
# Add NA as a factor level for categorical columns 
hData[categorical_cols] = lapply(hData[categorical_cols], addNA)
str(hData)
```

```{r}
# Make a histogram of rent values
p = ggplot(data = hData) +
  geom_histogram(aes(x = rent, y = after_stat(count)), breaks = seq(mean(hData$rent)-4*sd(hData$rent), mean(hData$rent)+4*sd(hData$rent), by = 25000), color = 'black', fill = 'blue') +
  labs(x = 'Rent', y = 'Frequency') +
  ggtitle('Histogram of house rents') +
  My_Theme
p
```

```{r}
# Make a scatter plot between price per square feet and rent
p = ggplot(data = hData) +
  geom_point(aes(x = rent , y = price_per_sqft)) +
  labs(x = 'Rent (Rupees)', y = 'Price per square feet (Rupees)') +
  ggtitle('Price per sqft vs. rent') +
  My_Theme
p
```

```{r}
# Build a linear model to predict price per square feet as a function of rent. How accurate is the model?
model1 = lm(data = hData, price_per_sqft ~ rent)
summary(model1)
```

```{r}
# Make a histogram of log-transformed rent values
hData['logrent'] = log(hData$rent)
p = ggplot(data = hData) +
  geom_histogram(aes(x = logrent, y = after_stat(count)), breaks = seq(mean(hData$logrent)-4*sd(hData$logrent), mean(hData$logrent)+4*sd(hData$logrent), by = 0.5), color = 'black', fill = 'blue') +
  labs(x = 'Rent', y = 'Frequency')    +
  ggtitle('Histogram of log of house rents') + 
  My_Theme
p
```
```{r}
plot(hData$rent)
hist(hData$rent)
hist(log(hData$rent))
hist(sqrt(hData$rent))
hist((hData$rent)^0.25)
```

```{r}
# Build a linear model to predict price per square feet as a function of logrent. Did log-transforming rent help improve the model accuracy?
model2 = lm(data = hData, price_per_sqft ~ logrent)
summary(model2)
```

```{r}
# Build a linear model to predict log of price per square feet as a function of logrent. Did log-transforming the response variable price per square feet improve the model accuracy?
hData['logprice_per_sqft'] = log(hData$price_per_sqft)
model3 = lm(data = hData, logprice_per_sqft ~ logrent)
summary(model3)                                 
```

```{r}
# Build a linear model to predict price per square feet as a function of sqrtrent. Did sqrt-transforming the predictor rent feet improve the model accuracy?
hData['sqrtrent'] = sqrt(hData$rent)
model4 = lm(data = hData, price_per_sqft ~ sqrtrent)
summary(model4)
```

```{r}
# Build a linear model to predict sqrt of price per square feet as a function of logrent. Did sqrt-transforming the response variable price per square feet improve the model accuracy?
hData['sqrtprice_per_sqft'] = sqrt(hData$price_per_sqft)
model5 = lm(data = hData, sqrtprice_per_sqft ~ logrent)
summary(model5)                     
```

```{r}
# Predict price per square feet for a new house
hDataNew = data.frame(7500, log(35000))
colnames(hDataNew) = c('price_per_sqft', 'logrent')
head(hDataNew)
predict(model2, hDataNew)
```

```{r}
# Split the dataframe into train and test parts
ind = sample(1:nrow(hData), size = 0.8*nrow(hData), replace = FALSE)
hData_train = hData[ind, ]
hData_test = hData[-ind, ]
```

```{r}
# Build a linear model to predict sqrt of price per square feet as a function of logrent using the train part of the dataset
model = lm(data = hData_train, sqrtprice_per_sqft ~ logrent)
summary(model)
```

```{r}
# Apply the model to the test part of the dataset
hData_test['predicted_price_per_sqft'] = predict(model, hData_test)^2
cbind(hData_test['predicted_price_per_sqft'], hData_test['price_per_sqft'])
```

```{r}
# Plot of the true and predicted prices for the test dataset
p = ggplot(data = hData_test) +
  geom_point(aes(x = price_per_sqft, y = predicted_price_per_sqft))+
  geom_abline(slope = 1, intercept = 0, col = 'red')
p
```

```{r}
# Test error of the model (Out-of-training-sample error estimate) = RMSE on the test dataset 
sqrt(mean((hData_test$price_per_sqft - hData_test$predicted_price_per_sqft)^2))
```

```{r}
# Build a multiple linear regression model to predict sqrt of price per sqft as a function of logrent, area, and locality
model7 = lm(data = hData_train, sqrtprice_per_sqft ~ logrent + area + locality)
summary(model7)
```

```{r}
# Apply the model to the test part of the dataset
hData_test['predicted_price_per_sqft'] = predict(model7, hData_test)^2
cbind(hData_test['predicted_price_per_sqft'], hData_test['price_per_sqft'])
```

```{r}
# Plot of the true and predicted prices for the test dataset
p = ggplot(data = hData_test) +
  geom_point(aes(x = price_per_sqft, y = predicted_price_per_sqft))+
  geom_abline(slope = 1, intercept = 0, col = 'red')
p
```

```{r}
# Test error of the model (Out-of-training-sample error estimate) = RMSE on the test dataset 
sqrt(mean((hData_test$price_per_sqft - hData_test$predicted_price_per_sqft)^2))
```
